{
 "title": "Detector 1 Biu 1 Details",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "BIU", "query": "${VAR_BIU}" },
   { "name": "DETECTOR", "query": "${VAR_DETECTOR}" },
   { "name": "HOST", "query": "${VAR_HOST}" }
  ]
 },
 "panels": [
  { "title": "Detector metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Detector count intervals",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 20, "x": 0, "y": 1 },
   "targets": [
    {
     "alias": "Count (1m interval)",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "detectors",
     "query": "SELECT count(\"count\") FROM \"detectors\" WHERE (\"biu\"::tag =~ /^$BIU$/ AND \"detector\"::tag =~ /^$DETECTOR$/ AND \"host\"::tag =~ /^$HOST$/ AND \"on\"=true) AND $timeFilter GROUP BY time(1m) fill(null)",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "biu::tag", "operator": "=~", "value": "/^$BIU$/" },
      { "condition": "AND", "key": "detector::tag", "operator": "=~", "value": "/^$DETECTOR$/" }
     ]
    },
    {
     "alias": "Count (5m interval)",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "detectors",
     "query": "SELECT count(\"count\") FROM \"detectors\" WHERE (\"biu\"::tag =~ /^$BIU$/ AND \"detector\"::tag =~ /^$DETECTOR$/ AND \"host\"::tag =~ /^$HOST$/ AND \"on\"=true) AND $timeFilter GROUP BY time(5m) fill(null)",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "biu::tag", "operator": "=~", "value": "/^$BIU$/" },
      { "condition": "AND", "key": "detector::tag", "operator": "=~", "value": "/^$DETECTOR$/" }
     ]
    },
    {
     "alias": "Count (15m interval)",
     "groupBy": [
      { "params": [ "15m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "detectors",
     "query": "SELECT count(\"count\") FROM \"detectors\" WHERE (\"biu\"::tag =~ /^$BIU$/ AND \"detector\"::tag =~ /^$DETECTOR$/ AND \"host\"::tag =~ /^$HOST$/ AND \"on\"=true) AND $timeFilter GROUP BY time(15m) fill(null)",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "biu::tag", "operator": "=~", "value": "/^$BIU$/" },
      { "condition": "AND", "key": "detector::tag", "operator": "=~", "value": "/^$DETECTOR$/" }
     ]
    },
    {
     "alias": "Count (30m interval)",
     "query": "SELECT count(\"count\") FROM \"detectors\" WHERE (\"biu\"::tag =~ /^$BIU$/ AND \"detector\"::tag =~ /^$DETECTOR$/ AND \"host\"::tag =~ /^$HOST$/ AND \"on\"=true) AND $timeFilter GROUP BY time(30m) fill(null)"
    },
    {
     "alias": "Count (1h interval)",
     "query": "SELECT count(\"count\") FROM \"detectors\" WHERE (\"biu\"::tag =~ /^$BIU$/ AND \"detector\"::tag =~ /^$DETECTOR$/ AND \"host\"::tag =~ /^$HOST$/ AND \"on\"=true) AND $timeFilter GROUP BY time(1h) fill(null)"
    }
   ]
  },
  {
   "title": "Detections",
   "type": "stat",
   "gridPos": { "h": 9, "w": 4, "x": 20, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "detectors",
     "query": "SELECT count(\"count\") FROM \"detectors\" WHERE (\"biu\"::tag =~ /^$BIU$/ AND \"detector\"::tag =~ /^$DETECTOR$/ AND \"host\"::tag =~ /^$HOST$/ AND \"on\"=true) AND $timeFilter",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "biu::tag", "operator": "=", "value": "1" },
      { "condition": "AND", "key": "detector::tag", "operator": "=", "value": "10" }
     ]
    }
   ]
  },
  {
   "title": "Detector change counter",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "alias": "Detector count since last reboot",
     "measurement": "detectors",
     "query": "SELECT        \"count\" FROM \"detectors\" WHERE (\"biu\"::tag =~ /^$BIU$/ AND \"detector\"::tag =~ /^$DETECTOR$/ AND \"host\"::tag =~ /^$HOST$/ AND \"on\"=true) AND $timeFilter\n",
     "select": [
      [
       { "params": [ "count" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "biu::tag", "operator": "=", "value": "$BIU" },
      { "condition": "AND", "key": "detector::tag", "operator": "=", "value": "$DETECTOR" }
     ]
    }
   ]
  },
  {
   "title": "Detector state",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "alias": "Calls",
     "measurement": "detectors",
     "query": "SELECT           \"on\" FROM \"detectors\" WHERE (\"biu\"::tag =~ /^$BIU$/ AND \"detector\"::tag =~ /^$DETECTOR$/ AND \"host\"::tag =~ /^$HOST$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "on" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "biu::tag", "operator": "=", "value": "$BIU" },
      { "condition": "AND", "key": "detector::tag", "operator": "=", "value": "$DETECTOR" }
     ]
    }
   ]
  },
  {
   "title": "Detector Tabular Report",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 26 },
   "targets": [
    {
     "query": "SELECT           \"on\", \"driver\" FROM \"detectors\" WHERE (\"biu\"::tag =~ /^$BIU$/ AND \"detector\"::tag =~ /^$DETECTOR$/ AND \"host\"::tag =~ /^$HOST$/) AND $timeFilter"
    }
   ]
  },
  {
   "title": "Longest OFF",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 34 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "detectors",
     "query": "SELECT max(\"lastLength\") FROM \"detectors\" WHERE (\"biu\"::tag =~ /^$BIU$/ AND \"detector\"::tag =~ /^$DETECTOR$/ AND \"host\"::tag =~ /^$HOST$/ AND \"on\"=false) AND $timeFilter",
     "select": [
      [
       { "params": [ "lastLength" ], "type": "field" }
      ],
      [
       { "params": [ "on" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "biu::tag", "operator": "=", "value": "1" },
      { "condition": "AND", "key": "detector::tag", "operator": "=", "value": "10" }
     ]
    }
   ]
  },
  {
   "title": "Shortest OFF",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 34 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "detectors",
     "query": "SELECT min(\"lastLength\") FROM \"detectors\" WHERE (\"biu\"::tag =~ /^$BIU$/ AND \"detector\"::tag =~ /^$DETECTOR$/ AND \"host\"::tag =~ /^$HOST$/ AND \"on\"=false) AND $timeFilter",
     "select": [
      [
       { "params": [ "lastLength" ], "type": "field" }
      ],
      [
       { "params": [ "on" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "biu::tag", "operator": "=", "value": "1" },
      { "condition": "AND", "key": "detector::tag", "operator": "=", "value": "10" }
     ]
    }
   ]
  },
  {
   "title": "Detector ON length histogram",
   "type": "histogram",
   "gridPos": { "h": 4, "w": 18, "x": 6, "y": 34 },
   "targets": [
    {
     "alias": "Detector ON",
     "query": "SELECT \"lastLength\", \"on\" FROM \"detectors\" WHERE (\"biu\"::tag =~ /^$BIU$/ AND \"detector\"::tag =~ /^$DETECTOR$/ AND \"host\"::tag =~ /^$HOST$/ AND \"on\"=true) AND $timeFilter"
    }
   ]
  },
  {
   "title": "Longest ON",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 38 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "detectors",
     "query": "SELECT max(\"lastLength\") FROM \"detectors\" WHERE (\"biu\"::tag =~ /^$BIU$/ AND \"detector\"::tag =~ /^$DETECTOR$/ AND \"host\"::tag =~ /^$HOST$/ AND \"on\"=true) AND $timeFilter",
     "select": [
      [
       { "params": [ "lastLength" ], "type": "field" }
      ],
      [
       { "params": [ "on" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "biu::tag", "operator": "=", "value": "1" },
      { "condition": "AND", "key": "detector::tag", "operator": "=", "value": "10" }
     ]
    }
   ]
  },
  {
   "title": "Shortest ON",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 38 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "detectors",
     "query": "SELECT min(\"lastLength\") FROM \"detectors\" WHERE (\"biu\"::tag =~ /^$BIU$/ AND \"detector\"::tag =~ /^$DETECTOR$/ AND \"host\"::tag =~ /^$HOST$/ AND \"on\"=true) AND $timeFilter",
     "select": [
      [
       { "params": [ "lastLength" ], "type": "field" }
      ],
      [
       { "params": [ "on" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "biu::tag", "operator": "=", "value": "1" },
      { "condition": "AND", "key": "detector::tag", "operator": "=", "value": "10" }
     ]
    }
   ]
  },
  {
   "title": "Detector OFF length histogram",
   "type": "histogram",
   "gridPos": { "h": 4, "w": 18, "x": 6, "y": 38 },
   "targets": [
    {
     "alias": "Detector OFF",
     "query": "SELECT \"lastLength\", \"on\" FROM \"detectors\" WHERE (\"biu\"::tag =~ /^$BIU$/ AND \"detector\"::tag =~ /^$DETECTOR$/ AND \"host\"::tag =~ /^$HOST$/ AND \"on\"=false) AND $timeFilter"
    }
   ]
  },
  {
   "title": "Detection phases",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 },
   "collapsed": true
  },
  {
   "title": "Arrivals on GREEN",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 43 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "detectors",
     "query": "SELECT count(\"count\")     FROM \"detectors\" WHERE (\"biu\"::tag =~ /^$BIU$/ AND \"detector\"::tag =~ /^$DETECTOR$/ AND \"host\"::tag =~ /^$HOST$/ AND \"driver\" = 2 AND \"on\" = true) AND $timeFilter",
     "select": [
      [
       { "params": [ "on" ], "type": "field" }
      ],
      [
       { "params": [ "driver" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "biu::tag", "operator": "=", "value": "1" },
      { "condition": "AND", "key": "detector::tag", "operator": "=", "value": "10" }
     ]
    }
   ]
  },
  {
   "title": "Arrivals on YELLOW",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 43 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "detectors",
     "query": "SELECT count(\"count\")     FROM \"detectors\" WHERE (\"biu\"::tag =~ /^$BIU$/ AND \"detector\"::tag =~ /^$DETECTOR$/ AND \"host\"::tag =~ /^$HOST$/ AND \"driver\" = 1 AND \"on\" = true) AND $timeFilter\n",
     "select": [
      [
       { "params": [ "on" ], "type": "field" }
      ],
      [
       { "params": [ "driver" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "biu::tag", "operator": "=", "value": "1" },
      { "condition": "AND", "key": "detector::tag", "operator": "=", "value": "10" }
     ]
    }
   ]
  },
  {
   "title": "Arrivals on RED",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 43 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "detectors",
     "query": "SELECT count(\"count\")     FROM \"detectors\" WHERE (\"biu\"::tag =~ /^$BIU$/ AND \"detector\"::tag =~ /^$DETECTOR$/ AND \"host\"::tag =~ /^$HOST$/ AND \"driver\" = 0 AND \"on\" = true) AND $timeFilter\n",
     "select": [
      [
       { "params": [ "on" ], "type": "field" }
      ],
      [
       { "params": [ "driver" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "biu::tag", "operator": "=", "value": "1" },
      { "condition": "AND", "key": "detector::tag", "operator": "=", "value": "10" }
     ]
    }
   ]
  },
  {
   "title": "Arrivals on GREEN intervals",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 8, "x": 0, "y": 47 },
   "targets": [
    {
     "alias": "Arrivals on GREEN interval 1 min",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "detectors",
     "query": "SELECT count(\"count\")     FROM \"detectors\" WHERE (\"biu\"::tag =~ /^$BIU$/ AND \"detector\"::tag =~ /^$DETECTOR$/ AND \"host\"::tag =~ /^$HOST$/ AND \"driver\" = 2 AND \"on\" = true) AND $timeFilter GROUP BY time(1m) fill(0)",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "biu::tag", "operator": "=", "value": "1" },
      { "condition": "AND", "key": "detector::tag", "operator": "=", "value": "10" }
     ]
    },
    {
     "alias": "Arrivals on GREEN interval 5 min",
     "query": "SELECT count(\"count\")     FROM \"detectors\" WHERE (\"biu\"::tag =~ /^$BIU$/ AND \"detector\"::tag =~ /^$DETECTOR$/ AND \"host\"::tag =~ /^$HOST$/ AND \"driver\" = 2 AND \"on\" = true) AND $timeFilter GROUP BY time(5m) fill(0)"
    },
    {
     "alias": "Arrivals on GREEN interval 15 min",
     "query": "SELECT count(\"count\")     FROM \"detectors\" WHERE (\"biu\"::tag =~ /^$BIU$/ AND \"detector\"::tag =~ /^$DETECTOR$/ AND \"host\"::tag =~ /^$HOST$/ AND \"driver\" = 2 AND \"on\" = true) AND $timeFilter GROUP BY time(15m) fill(0)"
    }
   ]
  },
  {
   "title": "Arrivals on YELLOW intervals",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 8, "x": 8, "y": 47 },
   "targets": [
    {
     "alias": "Arrivals on YELLOW interval 1 min",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "detectors",
     "query": "SELECT count(\"count\")     FROM \"detectors\" WHERE (\"biu\"::tag =~ /^$BIU$/ AND \"detector\"::tag =~ /^$DETECTOR$/ AND \"host\"::tag =~ /^$HOST$/ AND \"driver\" = 1 AND \"on\" = true) AND $timeFilter GROUP BY time(1m) fill(0)",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "biu::tag", "operator": "=", "value": "1" },
      { "condition": "AND", "key": "detector::tag", "operator": "=", "value": "10" }
     ]
    },
    {
     "alias": "Arrivals on YELLOW interval 5 min",
     "query": "SELECT count(\"count\")     FROM \"detectors\" WHERE (\"biu\"::tag =~ /^$BIU$/ AND \"detector\"::tag =~ /^$DETECTOR$/ AND \"host\"::tag =~ /^$HOST$/ AND \"driver\" = 1 AND \"on\" = true) AND $timeFilter GROUP BY time(5m) fill(0)"
    },
    {
     "alias": "Arrivals on YELLOW interval 15 min",
     "query": "SELECT count(\"count\")     FROM \"detectors\" WHERE (\"biu\"::tag =~ /^$BIU$/ AND \"detector\"::tag =~ /^$DETECTOR$/ AND \"host\"::tag =~ /^$HOST$/ AND \"driver\" = 1 AND \"on\" = true) AND $timeFilter GROUP BY time(15m) fill(0)"
    }
   ]
  },
  {
   "title": "Arrivals on RED intervals",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 8, "x": 16, "y": 47 },
   "targets": [
    {
     "alias": "Arrivals on RED interval 1 min",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "detectors",
     "query": "SELECT count(\"count\")     FROM \"detectors\" WHERE (\"biu\"::tag =~ /^$BIU$/ AND \"detector\"::tag =~ /^$DETECTOR$/ AND \"host\"::tag =~ /^$HOST$/ AND \"driver\" = 0 AND \"on\" = true) AND $timeFilter GROUP BY time(1m) fill(0)",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "biu::tag", "operator": "=", "value": "1" },
      { "condition": "AND", "key": "detector::tag", "operator": "=", "value": "10" }
     ]
    },
    {
     "alias": "Arrivals on RED interval 5 min",
     "query": "SELECT count(\"count\")     FROM \"detectors\" WHERE (\"biu\"::tag =~ /^$BIU$/ AND \"detector\"::tag =~ /^$DETECTOR$/ AND \"host\"::tag =~ /^$HOST$/ AND \"driver\" = 0 AND \"on\" = true) AND $timeFilter GROUP BY time(5m) fill(0)"
    },
    {
     "alias": "Arrivals on RED interval 15 min",
     "query": "SELECT count(\"count\")     FROM \"detectors\" WHERE (\"biu\"::tag =~ /^$BIU$/ AND \"detector\"::tag =~ /^$DETECTOR$/ AND \"host\"::tag =~ /^$HOST$/ AND \"driver\" = 0 AND \"on\" = true) AND $timeFilter GROUP BY time(15m) fill(0)"
    }
   ]
  },
  {
   "title": "Detections by phase",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 60 },
   "options": { "reduceOptions": { "calcs": [ "firstNotNull" ] } },
   "targets": [
    {
     "alias": "GREEN",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"count\") FROM \"detectors\" WHERE (\"biu\"::tag =~ /^$BIU$/ AND \"detector\"::tag =~ /^$DETECTOR$/ AND \"host\"::tag =~ /^$HOST$/ AND \"driver\" = 2 AND \"on\" = true) AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "YELLOW",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"count\") FROM \"detectors\" WHERE (\"biu\"::tag =~ /^$BIU$/ AND \"detector\"::tag =~ /^$DETECTOR$/ AND \"host\"::tag =~ /^$HOST$/ AND \"driver\" = 1 AND \"on\" = true) AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "RED",
     "query": "SELECT count(\"count\") FROM \"detectors\" WHERE (\"biu\"::tag =~ /^$BIU$/ AND \"detector\"::tag =~ /^$DETECTOR$/ AND \"host\"::tag =~ /^$HOST$/ AND \"driver\" = 0 AND \"on\" = true) AND $timeFilter"
    }
   ]
  }
 ]
}