{
 "title": "Detectors Summary",
 "time": { "from": "now-30d", "to": "now" },
 "templating": {
  "list": [
   { "name": "HOST", "query": "${VAR_HOST}" }
  ]
 },
 "panels": [
  {
   "title": "Biu 1 Det 1-8",
   "type": "piechart",
   "gridPos": { "h": 13, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Biu 1 Det 1",
     "measurement": "detectors",
     "query": "SELECT count(\"count\") FROM \"detectors\" WHERE (\"biu\"::tag = '1' AND \"detector\"::tag = '1' AND \"host\"::tag =~ /^$HOST$/ AND \"on\"=true) AND $timeFilter",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "biu::tag", "operator": "=", "value": "1" },
      { "condition": "AND", "key": "detector::tag", "operator": "=", "value": "1" }
     ]
    },
    {
     "alias": "Biu 1 Det 2",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"count\") FROM \"detectors\" WHERE (\"biu\"::tag = '1' AND \"detector\"::tag = '2' AND \"host\"::tag =~ /^$HOST$/ AND \"on\"=true) AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Biu 1 Det 3",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"count\") FROM \"detectors\" WHERE (\"biu\"::tag = '1' AND \"detector\"::tag = '3' AND \"host\"::tag =~ /^$HOST$/ AND \"on\"=true) AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Biu 1 Det 4",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"count\") FROM \"detectors\" WHERE (\"biu\"::tag = '1' AND \"detector\"::tag = '4' AND \"host\"::tag =~ /^$HOST$/ AND \"on\"=true) AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Biu 1 Det 5",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"count\") FROM \"detectors\" WHERE (\"biu\"::tag = '1' AND \"detector\"::tag = '5' AND \"host\"::tag =~ /^$HOST$/ AND \"on\"=true) AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Biu 1 Det 6",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"count\") FROM \"detectors\" WHERE (\"biu\"::tag = '1' AND \"detector\"::tag = '6' AND \"host\"::tag =~ /^$HOST$/ AND \"on\"=true) AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Biu 1 Det 7",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"count\") FROM \"detectors\" WHERE (\"biu\"::tag = '1' AND \"detector\"::tag = '7' AND \"host\"::tag =~ /^$HOST$/ AND \"on\"=true) AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Biu 1 Det 8",
     "query": "SELECT count(\"count\") FROM \"detectors\" WHERE (\"biu\"::tag = '1' AND \"detector\"::tag = '8' AND \"host\"::tag =~ /^$HOST$/ AND \"on\"=true) AND $timeFilter"
    }
   ]
  },
  {
   "title": "Biu 1 Det 9-16",
   "type": "piechart",
   "gridPos": { "h": 13, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Biu 1 Det 9",
     "measurement": "detectors",
     "query": "SELECT count(\"count\") FROM \"detectors\" WHERE (\"biu\"::tag = '1' AND \"detector\"::tag = '9' AND \"host\"::tag =~ /^$HOST$/ AND \"on\"=true) AND $timeFilter",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "biu::tag", "operator": "=", "value": "1" },
      { "condition": "AND", "key": "detector::tag", "operator": "=", "value": "1" }
     ]
    },
    {
     "alias": "Biu 1 Det 10",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"count\") FROM \"detectors\" WHERE (\"biu\"::tag = '1' AND \"detector\"::tag = '10' AND \"host\"::tag =~ /^$HOST$/ AND \"on\"=true) AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Biu 1 Det 11",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"count\") FROM \"detectors\" WHERE (\"biu\"::tag = '1' AND \"detector\"::tag = '11' AND \"host\"::tag =~ /^$HOST$/ AND \"on\"=true) AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Biu 1 Det 12",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"count\") FROM \"detectors\" WHERE (\"biu\"::tag = '1' AND \"detector\"::tag = '12' AND \"host\"::tag =~ /^$HOST$/ AND \"on\"=true) AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Biu 1 Det 13",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"count\") FROM \"detectors\" WHERE (\"biu\"::tag = '1' AND \"detector\"::tag = '13' AND \"host\"::tag =~ /^$HOST$/ AND \"on\"=true) AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Biu 1 Det 14",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"count\") FROM \"detectors\" WHERE (\"biu\"::tag = '1' AND \"detector\"::tag = '14' AND \"host\"::tag =~ /^$HOST$/ AND \"on\"=true) AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Biu 1 Det 15",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"count\") FROM \"detectors\" WHERE (\"biu\"::tag = '1' AND \"detector\"::tag = '15' AND \"host\"::tag =~ /^$HOST$/ AND \"on\"=true) AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Biu 1 Det 16",
     "query": "SELECT count(\"count\") FROM \"detectors\" WHERE (\"biu\"::tag = '1' AND \"detector\"::tag = '16' AND \"host\"::tag =~ /^$HOST$/ AND \"on\"=true) AND $timeFilter"
    }
   ]
  },
  {
   "title": "Biu 2 Det 1-8",
   "type": "piechart",
   "gridPos": { "h": 13, "w": 6, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Biu 2 Det 1",
     "measurement": "detectors",
     "query": "SELECT count(\"count\") FROM \"detectors\" WHERE (\"biu\"::tag = '2' AND \"detector\"::tag = '1' AND \"host\"::tag =~ /^$HOST$/ AND \"on\"=true) AND $timeFilter",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "biu::tag", "operator": "=", "value": "1" },
      { "condition": "AND", "key": "detector::tag", "operator": "=", "value": "1" }
     ]
    },
    {
     "alias": "Biu 2 Det 2",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"count\") FROM \"detectors\" WHERE (\"biu\"::tag = '2' AND \"detector\"::tag = '2' AND \"host\"::tag =~ /^$HOST$/ AND \"on\"=true) AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Biu 2 Det 3",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"count\") FROM \"detectors\" WHERE (\"biu\"::tag = '2' AND \"detector\"::tag = '3' AND \"host\"::tag =~ /^$HOST$/ AND \"on\"=true) AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Biu 2 Det 4",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"count\") FROM \"detectors\" WHERE (\"biu\"::tag = '2' AND \"detector\"::tag = '4' AND \"host\"::tag =~ /^$HOST$/ AND \"on\"=true) AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Biu 2 Det 5",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"count\") FROM \"detectors\" WHERE (\"biu\"::tag = '2' AND \"detector\"::tag = '5' AND \"host\"::tag =~ /^$HOST$/ AND \"on\"=true) AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Biu 2 Det 6",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"count\") FROM \"detectors\" WHERE (\"biu\"::tag = '2' AND \"detector\"::tag = '6' AND \"host\"::tag =~ /^$HOST$/ AND \"on\"=true) AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Biu 2 Det 7",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"count\") FROM \"detectors\" WHERE (\"biu\"::tag = '2' AND \"detector\"::tag = '7' AND \"host\"::tag =~ /^$HOST$/ AND \"on\"=true) AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Biu 2 Det 8",
     "query": "SELECT count(\"count\") FROM \"detectors\" WHERE (\"biu\"::tag = '2' AND \"detector\"::tag = '8' AND \"host\"::tag =~ /^$HOST$/ AND \"on\"=true) AND $timeFilter"
    }
   ]
  },
  {
   "title": "Biu 2 Det 9-16",
   "type": "piechart",
   "gridPos": { "h": 13, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Biu 2 Det 9",
     "measurement": "detectors",
     "query": "SELECT count(\"count\") FROM \"detectors\" WHERE (\"biu\"::tag = '2' AND \"detector\"::tag = '9' AND \"host\"::tag =~ /^$HOST$/ AND \"on\"=true) AND $timeFilter",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "biu::tag", "operator": "=", "value": "1" },
      { "condition": "AND", "key": "detector::tag", "operator": "=", "value": "1" }
     ]
    },
    {
     "alias": "Biu 2 Det 10",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"count\") FROM \"detectors\" WHERE (\"biu\"::tag = '1' AND \"detector\"::tag = '10' AND \"host\"::tag =~ /^$HOST$/ AND \"on\"=true) AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Biu 2 Det 11",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"count\") FROM \"detectors\" WHERE (\"biu\"::tag = '2' AND \"detector\"::tag = '11' AND \"host\"::tag =~ /^$HOST$/ AND \"on\"=true) AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Biu 2 Det 12",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"count\") FROM \"detectors\" WHERE (\"biu\"::tag = '2' AND \"detector\"::tag = '12' AND \"host\"::tag =~ /^$HOST$/ AND \"on\"=true) AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Biu 2 Det 13",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"count\") FROM \"detectors\" WHERE (\"biu\"::tag = '2' AND \"detector\"::tag = '13' AND \"host\"::tag =~ /^$HOST$/ AND \"on\"=true) AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Biu 2 Det 14",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"count\") FROM \"detectors\" WHERE (\"biu\"::tag = '2' AND \"detector\"::tag = '14' AND \"host\"::tag =~ /^$HOST$/ AND \"on\"=true) AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Biu 2 Det 15",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"count\") FROM \"detectors\" WHERE (\"biu\"::tag = '2' AND \"detector\"::tag = '15' AND \"host\"::tag =~ /^$HOST$/ AND \"on\"=true) AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Biu 2 Det 16",
     "query": "SELECT count(\"count\") FROM \"detectors\" WHERE (\"biu\"::tag = '2' AND \"detector\"::tag = '16' AND \"host\"::tag =~ /^$HOST$/ AND \"on\"=true) AND $timeFilter"
    }
   ]
  },
  {
   "title": "Biu 3 Det 1-8",
   "type": "piechart",
   "gridPos": { "h": 13, "w": 6, "x": 0, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Biu 3 Det 1",
     "measurement": "detectors",
     "query": "SELECT count(\"count\") FROM \"detectors\" WHERE (\"biu\"::tag = '3' AND \"detector\"::tag = '1' AND \"host\"::tag =~ /^$HOST$/ AND \"on\"=true) AND $timeFilter",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "biu::tag", "operator": "=", "value": "1" },
      { "condition": "AND", "key": "detector::tag", "operator": "=", "value": "1" }
     ]
    },
    {
     "alias": "Biu 3 Det 2",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"count\") FROM \"detectors\" WHERE (\"biu\"::tag = '3' AND \"detector\"::tag = '2' AND \"host\"::tag =~ /^$HOST$/ AND \"on\"=true) AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Biu 3 Det 3",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"count\") FROM \"detectors\" WHERE (\"biu\"::tag = '3' AND \"detector\"::tag = '3' AND \"host\"::tag =~ /^$HOST$/ AND \"on\"=true) AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Biu 3 Det 4",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"count\") FROM \"detectors\" WHERE (\"biu\"::tag = '3' AND \"detector\"::tag = '4' AND \"host\"::tag =~ /^$HOST$/ AND \"on\"=true) AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Biu 3 Det 5",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"count\") FROM \"detectors\" WHERE (\"biu\"::tag = '3' AND \"detector\"::tag = '5' AND \"host\"::tag =~ /^$HOST$/ AND \"on\"=true) AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Biu 3 Det 6",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"count\") FROM \"detectors\" WHERE (\"biu\"::tag = '3' AND \"detector\"::tag = '6' AND \"host\"::tag =~ /^$HOST$/ AND \"on\"=true) AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Biu 3 Det 7",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"count\") FROM \"detectors\" WHERE (\"biu\"::tag = '3' AND \"detector\"::tag = '7' AND \"host\"::tag =~ /^$HOST$/ AND \"on\"=true) AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Biu 3 Det 8",
     "query": "SELECT count(\"count\") FROM \"detectors\" WHERE (\"biu\"::tag = '3' AND \"detector\"::tag = '8' AND \"host\"::tag =~ /^$HOST$/ AND \"on\"=true) AND $timeFilter"
    }
   ]
  },
  {
   "title": "Biu 3 Det 9-16",
   "type": "piechart",
   "gridPos": { "h": 13, "w": 6, "x": 6, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Biu 3 Det 9",
     "measurement": "detectors",
     "query": "SELECT count(\"count\") FROM \"detectors\" WHERE (\"biu\"::tag = '3' AND \"detector\"::tag = '9' AND \"host\"::tag =~ /^$HOST$/ AND \"on\"=true) AND $timeFilter",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "biu::tag", "operator": "=", "value": "1" },
      { "condition": "AND", "key": "detector::tag", "operator": "=", "value": "1" }
     ]
    },
    {
     "alias": "Biu 3 Det 10",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"count\") FROM \"detectors\" WHERE (\"biu\"::tag = '3' AND \"detector\"::tag = '10' AND \"host\"::tag =~ /^$HOST$/ AND \"on\"=true) AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Biu 3 Det 11",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"count\") FROM \"detectors\" WHERE (\"biu\"::tag = '3' AND \"detector\"::tag = '11' AND \"host\"::tag =~ /^$HOST$/ AND \"on\"=true) AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Biu 3 Det 12",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"count\") FROM \"detectors\" WHERE (\"biu\"::tag = '3' AND \"detector\"::tag = '12' AND \"host\"::tag =~ /^$HOST$/ AND \"on\"=true) AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Biu 3 Det 13",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"count\") FROM \"detectors\" WHERE (\"biu\"::tag = '3' AND \"detector\"::tag = '13' AND \"host\"::tag =~ /^$HOST$/ AND \"on\"=true) AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Biu 3 Det 14",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"count\") FROM \"detectors\" WHERE (\"biu\"::tag = '3' AND \"detector\"::tag = '14' AND \"host\"::tag =~ /^$HOST$/ AND \"on\"=true) AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Biu 3 Det 15",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"count\") FROM \"detectors\" WHERE (\"biu\"::tag = '3' AND \"detector\"::tag = '15' AND \"host\"::tag =~ /^$HOST$/ AND \"on\"=true) AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Biu 3 Det 16",
     "query": "SELECT count(\"count\") FROM \"detectors\" WHERE (\"biu\"::tag = '3' AND \"detector\"::tag = '16' AND \"host\"::tag =~ /^$HOST$/ AND \"on\"=true) AND $timeFilter"
    }
   ]
  },
  {
   "title": "Biu 4 Det 1-8",
   "type": "piechart",
   "gridPos": { "h": 13, "w": 6, "x": 12, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Biu 4 Det 1",
     "measurement": "detectors",
     "query": "SELECT count(\"count\") FROM \"detectors\" WHERE (\"biu\"::tag = '4' AND \"detector\"::tag = '1' AND \"host\"::tag =~ /^$HOST$/ AND \"on\"=true) AND $timeFilter",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "biu::tag", "operator": "=", "value": "1" },
      { "condition": "AND", "key": "detector::tag", "operator": "=", "value": "1" }
     ]
    },
    {
     "alias": "Biu 4 Det 2",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"count\") FROM \"detectors\" WHERE (\"biu\"::tag = '4' AND \"detector\"::tag = '2' AND \"host\"::tag =~ /^$HOST$/ AND \"on\"=true) AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Biu 4 Det 3",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"count\") FROM \"detectors\" WHERE (\"biu\"::tag = '4' AND \"detector\"::tag = '3' AND \"host\"::tag =~ /^$HOST$/ AND \"on\"=true) AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Biu 4 Det 4",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"count\") FROM \"detectors\" WHERE (\"biu\"::tag = '4' AND \"detector\"::tag = '4' AND \"host\"::tag =~ /^$HOST$/ AND \"on\"=true) AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Biu 4 Det 5",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"count\") FROM \"detectors\" WHERE (\"biu\"::tag = '4' AND \"detector\"::tag = '5' AND \"host\"::tag =~ /^$HOST$/ AND \"on\"=true) AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Biu 4 Det 6",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"count\") FROM \"detectors\" WHERE (\"biu\"::tag = '4' AND \"detector\"::tag = '6' AND \"host\"::tag =~ /^$HOST$/ AND \"on\"=true) AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Biu 4 Det 7",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"count\") FROM \"detectors\" WHERE (\"biu\"::tag = '4' AND \"detector\"::tag = '7' AND \"host\"::tag =~ /^$HOST$/ AND \"on\"=true) AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Biu 4 Det 8",
     "query": "SELECT count(\"count\") FROM \"detectors\" WHERE (\"biu\"::tag = '4' AND \"detector\"::tag = '8' AND \"host\"::tag =~ /^$HOST$/ AND \"on\"=true) AND $timeFilter"
    }
   ]
  },
  {
   "title": "Biu 4 Det 9-16",
   "type": "piechart",
   "gridPos": { "h": 13, "w": 6, "x": 18, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Biu 4 Det 9",
     "measurement": "detectors",
     "query": "SELECT count(\"count\") FROM \"detectors\" WHERE (\"biu\"::tag = '4' AND \"detector\"::tag = '9' AND \"host\"::tag =~ /^$HOST$/ AND \"on\"=true) AND $timeFilter",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "biu::tag", "operator": "=", "value": "1" },
      { "condition": "AND", "key": "detector::tag", "operator": "=", "value": "1" }
     ]
    },
    {
     "alias": "Biu 4 Det 10",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"count\") FROM \"detectors\" WHERE (\"biu\"::tag = '4' AND \"detector\"::tag = '10' AND \"host\"::tag =~ /^$HOST$/ AND \"on\"=true) AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Biu 4 Det 11",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"count\") FROM \"detectors\" WHERE (\"biu\"::tag = '4' AND \"detector\"::tag = '11' AND \"host\"::tag =~ /^$HOST$/ AND \"on\"=true) AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Biu 4 Det 12",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"count\") FROM \"detectors\" WHERE (\"biu\"::tag = '4' AND \"detector\"::tag = '12' AND \"host\"::tag =~ /^$HOST$/ AND \"on\"=true) AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Biu 4 Det 13",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"count\") FROM \"detectors\" WHERE (\"biu\"::tag = '4' AND \"detector\"::tag = '13' AND \"host\"::tag =~ /^$HOST$/ AND \"on\"=true) AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Biu 4 Det 14",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"count\") FROM \"detectors\" WHERE (\"biu\"::tag = '4' AND \"detector\"::tag = '14' AND \"host\"::tag =~ /^$HOST$/ AND \"on\"=true) AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Biu 4 Det 15",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"count\") FROM \"detectors\" WHERE (\"biu\"::tag = '4' AND \"detector\"::tag = '15' AND \"host\"::tag =~ /^$HOST$/ AND \"on\"=true) AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Biu 4 Det 16",
     "query": "SELECT count(\"count\") FROM \"detectors\" WHERE (\"biu\"::tag = '4' AND \"detector\"::tag = '16' AND \"host\"::tag =~ /^$HOST$/ AND \"on\"=true) AND $timeFilter"
    }
   ]
  }
 ]
}