{
 "title": "Device Status",
 "time": { "from": "2024-12-01T14:24:17.530Z", "to": "2024-12-01T18:19:53.089Z" },
 "templating": {
  "list": [
   { "name": "HOST", "query": "${VAR_HOST}" }
  ]
 },
 "panels": [
  { "title": "Location", "type": "geomap", "gridPos": { "h": 11, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "System voltages",
   "type": "timeseries",
   "gridPos": { "h": 26, "w": 6, "x": 0, "y": 11 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "status",
     "query": "SELECT mean(\"fivevolts\") FROM \"status\" WHERE (\"name\"::tag = 'Location') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "fivevolts" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=~", "value": "/^$HOST$/" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "status",
     "select": [
      [
       { "params": [ "involts" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=~", "value": "/^$HOST$/" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "status",
     "select": [
      [
       { "params": [ "threevolts" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=~", "value": "/^$HOST$/" }
     ]
    }
   ]
  },
  {
   "title": "Uptime seconds",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 18, "x": 6, "y": 11 },
   "targets": [
    {
     "alias": "device",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "status",
     "query": "SELECT mean(\"uptime\") FROM \"status\" WHERE (\"host\"::tag =~ /^$HOST$/) AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "uptime" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=~", "value": "/^$HOST$/" }
     ]
    },
    {
     "alias": "logger",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "status",
     "query": "SELECT mean(\"running\") FROM \"status\" WHERE (\"host\"::tag =~ /^$HOST$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "running" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=~", "value": "/^$HOST$/" }
     ]
    }
   ]
  },
  {
   "title": "Device reachable",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 18, "x": 6, "y": 21 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "status",
     "query": "SELECT last(\"reachable\") FROM \"status\" WHERE (\"host\"::tag =~ /^$HOST$/) AND $timeFilter GROUP BY time($interval)",
     "select": [
      [
       { "params": [ "reachable" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "name::tag", "operator": "=~", "value": "/^$HOST$/" }
     ]
    }
   ]
  },
  {
   "title": "Device time synced",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 18, "x": 6, "y": 25 },
   "targets": [
    {
     "measurement": "status",
     "query": "SELECT last(\"timeSynced\") FROM \"status\" WHERE (\"host\"::tag =~ /^$HOST$/) AND $timeFilter GROUP BY time($interval)",
     "select": [
      [
       { "params": [ "timeSynced" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "name::tag", "operator": "=", "value": "Location" }
     ]
    }
   ]
  },
  {
   "title": "Device status",
   "type": "table",
   "gridPos": { "h": 8, "w": 18, "x": 6, "y": 29 },
   "targets": [
    {
     "measurement": "status",
     "query": "SELECT \"system\" FROM \"status\" WHERE (\"host\"::tag =~ /^$HOST$/) AND $timeFilter ORDER BY time DESC",
     "select": [
      [
       { "params": [ "system" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "name::tag", "operator": "=", "value": "Location" }
     ]
    }
   ]
  }
 ]
}