{
 "title": "Load Switches Summary",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Load switch 1 Average green",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "measurement": "loadswitches",
     "query": "SELECT \"lastLength\" FROM \"loadswitches\" WHERE (\"host\"::tag = '192.168.14.34' AND \"loadswitch\"::tag = '1' AND \"lastDriver\" = 2) AND $timeFilter",
     "select": [
      [
       { "params": [ "lastLength" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=", "value": "192.168.14.34" },
      { "condition": "AND", "key": "loadswitch::tag", "operator": "=", "value": "1" }
     ]
    }
   ]
  },
  {
   "title": "Load switch 2 Average green",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "measurement": "loadswitches",
     "query": "SELECT \"lastLength\" FROM \"loadswitches\" WHERE (\"host\"::tag = '192.168.14.34' AND \"loadswitch\"::tag = '2' AND \"lastDriver\" = 2) AND $timeFilter",
     "select": [
      [
       { "params": [ "lastLength" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=", "value": "192.168.14.34" },
      { "condition": "AND", "key": "loadswitch::tag", "operator": "=", "value": "1" }
     ]
    }
   ]
  },
  {
   "title": "Load switch 3 Average green",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "measurement": "loadswitches",
     "query": "SELECT \"lastLength\" FROM \"loadswitches\" WHERE (\"host\"::tag = '192.168.14.34' AND \"loadswitch\"::tag = '3' AND \"lastDriver\" = 2) AND $timeFilter",
     "select": [
      [
       { "params": [ "lastLength" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=", "value": "192.168.14.34" },
      { "condition": "AND", "key": "loadswitch::tag", "operator": "=", "value": "1" }
     ]
    }
   ]
  },
  {
   "title": "Load switch 4 Average green",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "measurement": "loadswitches",
     "query": "SELECT \"lastLength\" FROM \"loadswitches\" WHERE (\"host\"::tag = '192.168.14.34' AND \"loadswitch\"::tag = '4' AND \"lastDriver\" = 2) AND $timeFilter",
     "select": [
      [
       { "params": [ "lastLength" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=", "value": "192.168.14.34" },
      { "condition": "AND", "key": "loadswitch::tag", "operator": "=", "value": "1" }
     ]
    }
   ]
  },
  {
   "title": "Load switch 5 Average green",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "measurement": "loadswitches",
     "query": "SELECT \"lastLength\" FROM \"loadswitches\" WHERE (\"host\"::tag = '192.168.14.34' AND \"loadswitch\"::tag = '5' AND \"lastDriver\" = 2) AND $timeFilter",
     "select": [
      [
       { "params": [ "lastLength" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=", "value": "192.168.14.34" },
      { "condition": "AND", "key": "loadswitch::tag", "operator": "=", "value": "1" }
     ]
    }
   ]
  },
  {
   "title": "Load switch 6 Average green",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 15, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "measurement": "loadswitches",
     "query": "SELECT \"lastLength\" FROM \"loadswitches\" WHERE (\"host\"::tag = '192.168.14.34' AND \"loadswitch\"::tag = '6' AND \"lastDriver\" = 2) AND $timeFilter",
     "select": [
      [
       { "params": [ "lastLength" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=", "value": "192.168.14.34" },
      { "condition": "AND", "key": "loadswitch::tag", "operator": "=", "value": "1" }
     ]
    }
   ]
  },
  {
   "title": "Load switch 7 Average green",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "measurement": "loadswitches",
     "query": "SELECT \"lastLength\" FROM \"loadswitches\" WHERE (\"host\"::tag = '192.168.14.34' AND \"loadswitch\"::tag = '7' AND \"lastDriver\" = 2) AND $timeFilter",
     "select": [
      [
       { "params": [ "lastLength" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=", "value": "192.168.14.34" },
      { "condition": "AND", "key": "loadswitch::tag", "operator": "=", "value": "1" }
     ]
    }
   ]
  },
  {
   "title": "Load switch 8 Average green",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "measurement": "loadswitches",
     "query": "SELECT \"lastLength\" FROM \"loadswitches\" WHERE (\"host\"::tag = '192.168.14.34' AND \"loadswitch\"::tag = '8' AND \"lastDriver\" = 2) AND $timeFilter",
     "select": [
      [
       { "params": [ "lastLength" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=", "value": "192.168.14.34" },
      { "condition": "AND", "key": "loadswitch::tag", "operator": "=", "value": "1" }
     ]
    }
   ]
  }
 ]
}