{
 "title": "Load Switch 1",
 "time": { "from": "2024-11-30T01:25:26.821Z", "to": "2024-11-30T11:30:51.146Z" },
 "templating": {
  "list": [
   { "name": "LOADSWITCH", "query": "${VAR_LOADSWITCH}" },
   { "name": "HOST", "query": "${VAR_HOST}" }
  ]
 },
 "panels": [
  {
   "title": "Average red seconds",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "loadswitches",
     "query": "SELECT mean(\"lastLength\") FROM \"loadswitches\" WHERE (\"loadswitch\"::tag =~ /^$LOADSWITCH$/ AND \"host\"::tag =~ /^$HOST$/ AND lastDriver=0) AND $timeFilter",
     "select": [
      [
       { "params": [ "lastLength" ], "type": "field" }
      ],
      [
       { "params": [ "lastDriver" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "loadswitch::tag", "operator": "=", "value": "1" }
     ]
    }
   ]
  },
  {
   "title": "Average yellow seconds",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "loadswitches",
     "query": "SELECT mean(\"lastLength\") FROM \"loadswitches\" WHERE (\"loadswitch\"::tag =~ /^$LOADSWITCH$/ AND \"host\"::tag =~ /^$HOST$/ AND lastDriver=1) AND $timeFilter",
     "select": [
      [
       { "params": [ "lastLength" ], "type": "field" }
      ],
      [
       { "params": [ "lastDriver" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "loadswitch::tag", "operator": "=", "value": "1" }
     ]
    }
   ]
  },
  {
   "title": "Average green seconds",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "loadswitches",
     "query": "SELECT mean(\"lastLength\") FROM \"loadswitches\" WHERE (\"loadswitch\"::tag =~ /^$LOADSWITCH$/ AND \"host\"::tag =~ /^$HOST$/ AND lastDriver=2) AND $timeFilter",
     "select": [
      [
       { "params": [ "lastLength" ], "type": "field" }
      ],
      [
       { "params": [ "lastDriver" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "loadswitch::tag", "operator": "=", "value": "1" }
     ]
    }
   ]
  },
  {
   "title": "Time in each color",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "GREEN",
     "measurement": "loadswitches",
     "query": "SELECT \"lastLength\" FROM \"loadswitches\" WHERE (\"loadswitch\"::tag =~ /^$LOADSWITCH$/ AND \"host\"::tag =~ /^$HOST$/ AND \"lastDriver\"=2) AND $timeFilter",
     "select": [
      [
       { "params": [ "lastLength" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "loadswitch::tag", "operator": "=~", "value": "/^$LOADSWITCH$/" }
     ]
    },
    {
     "alias": "YELLOW",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"lastLength\" FROM \"loadswitches\" WHERE (\"loadswitch\"::tag =~ /^$LOADSWITCH$/ AND \"host\"::tag =~ /^$HOST$/ AND \"lastDriver\"=1) AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "RED",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"lastLength\" FROM \"loadswitches\" WHERE (\"loadswitch\"::tag =~ /^$LOADSWITCH$/  AND \"host\"::tag =~ /^$HOST$/ AND \"lastDriver\"=0) AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Load switch mode",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "measurement": "loadswitches",
     "query": "SELECT \"lastDriver\", \"driver\" FROM \"loadswitches\" WHERE (\"loadswitch\"::tag =~ /^$LOADSWITCH$/ AND \"host\"::tag =~ /^$HOST$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "lastDriver" ], "type": "field" }
      ],
      [
       { "params": [ "driver" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "loadswitch::tag", "operator": "=", "value": "1" }
     ]
    }
   ]
  },
  {
   "title": "Last phase length seconds",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "measurement": "loadswitches",
     "query": "SELECT \"lastLength\" FROM \"loadswitches\" WHERE (\"loadswitch\"::tag =~ /^$LOADSWITCH$/ AND \"host\"::tag =~ /^$HOST$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "lastLength" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "loadswitch::tag", "operator": "=", "value": "1" }
     ]
    }
   ]
  }
 ]
}